### ISSUE TITLE
крашит бота

### ISSUE THREAD

**Issue by mynameisdavis** [TastyBread123/WonderfulBot#2]
всем привет!
настроил бота в файле, но его крашит при запуске. 
![Screenshot_21](https://user-images.githubusercontent.com/101875041/235351134-589885df-4da6-41a6-8e11-f7b29584cdac.png)

**Comment by TastyBread123** [comment]
Скорее всего, версия aiogram устарела

Скачайте с помощью данной команды pip install aiogram -U --pre
